export default {
    en: {
        hero: { quote: "I dev stuff on the Web for the World", title: "Full-stack Web Engineer" },
        footer: {
            github: { text: "", label: "GitHub link" },
            mail: { text: "", label: "Mail address" },
            linkedin: { text: "", label: "Linkedin link" },
            resume: { text: "My Resume", label: "Resume file", url: "/resume_en.pdf" },
        },
        button: {
            seeMore: "See More",
            viewOn: "View on",
            back: "Back",
        },
        nav: { about: "about", experience: "experience", projects: "projects", skills: "skills" },
        projects: {
            type: { personal: "Personal", academic: "Academic" },
            sna: {
                date: "2024",
                title: "Autonomous Social Network Accounts",
                desc: "This project entailed developing a Python-based Social Networks automation solution. Key features include data extraction, AI-powered content generation, automated post uploads, and community engagement. A whole architecture was designed to manage multiple accounts and tasks.",
                details: {
                    intro: "This project aims to develop a <b>complete automation solution for social media</b>, using <b>Flask, Vue.js, Node.js, Remotion, Redis, Celery, MySQL, and Docker</b>. The key features of this solution include data extraction, AI-assisted content generation, and automatic posting. The designed architecture is robust, allowing for <b>simultaneous management of multiple accounts and various tasks</b>.",
                    video: "An example of this solution can be observed through a demonstration video. The core content of the video, a poem, is generated by a large language model (<b>LLM</b>). Additionally, the video incorporates a royalty-free background, carefully selected and adapted for the occasion. The <b>subtitles</b>, enriched with emojis, are synchronized with the </b>text narration</b> by a generative AI. A soundtrack accompanies the whole to enhance the experience.",
                    outro: "The final video is <b>published</b> on the relevant account with a <b>description and a thumbnail</b> to attract and engage the target audience.",
                    media: {
                        video: "Example of a video",
                    },
                },
            },
            ml: {
                date: "2022",
                title: "Machine Learning Model",
                desc: "Creation of a machine learning model in Python to predict revenue of all types of retail stores in Norway",
            },
            ayc: {
                date: "2022",
                title: "Autonomous Youtube Channel",
                desc: 'This project involved crafting a YouTube channel dedicated to daily "best-of" compilations of top Twitch clips, enhanced with fancy overlays to enrich user experience. Utilizing Python for channel management, tasks encompassed data scrapping, resource acquisition, and content selection & creation.',
                details: {
                    intro: "This is <b>my first personal programming project</b>, and notably my learning of <b>Python, APIs, FFmpeg, Docker, and hosting on a VPS</b>. It involved developing a YouTube channel specializing in daily compilations of the <b>best Twitch clips</b>. The goal was to enrich the <b>user experience</b> with graphic assets. The project relies on Twitch's API for <b>scraping and storing</b> data, and also involves <b>resource acquisition</b>, <b>content selection</b>, and its <b>automatic publication</b>.",
                    video: "Each compiled video featured a <b>dynamic structure</b>: at the top left, a <b>summary</b> displayed the names of the streamers, on the right was the selected <b>Twitch clip</b>, at the bottom left the <b>thumbnail of the game</b> in question, and at the bottom right the <b>title of the clip</b>. Calls to action for sharing and subscribing (<b>Call to Action</b>) were integrated throughout the video, complemented by an outro at the end of the video.",
                    thumbnail:
                        "The <b>thumbnails</b> of each video were designed to capture the viewers' attention, with bright colors and eye-catching graphic elements. The <b>most popular streamers were highlighted</b> in the center with predefined images, while the profile photos of other streamers appeared in side circles. The episode number and a screenshot of two viral clips formed the background, with the option to vary the colors of the background, title, and numbers according to <b>several combinations</b>.",
                    text: "A <b>title</b> was automatically generated for each video, featuring the popular streamers present. A <b>description</b> created a precise timeline for each included clip, thus facilitating navigation through the video.",
                    media: {
                        video: "Video extract",
                        cta: "Example of Call to Action",
                        thumbnail: "Video thumbnail",
                    },
                },
            },
            dw: {
                date: "2021",
                title: "Dynamic Website",
                desc: "Vaccination site in HTML, CSS, PHP, SQL with management of the various functionalities from a provider point of view",
            },
        },
        experience: {
            grytics: {
                title: "Assistant Development Engineer",
                desc: "At Grytics, I conducted functional testing and developed a machine learning/AI proof-of-concept (R&D) for improving their web application. Working independently under the lead developer, I honed my skills in maintainable code and efficient problem-solving, contributing to the application's robustness and showcasing potential future enhancements.",
                date: "FEB 2023 - JUL 2023",
            },
            selectra: {
                title: "Full-stack Web Engineer",
                desc: "At Selectra, I integrated new features, refactored databases and services, and fixed issues using Vue.js and Laravel, enhancing both the stability and performance of the platforms. I advanced user experience and project efficiency through process optimization and API integration between projects. I worked in a resilient, rigorous and  various monolithic environments, aiming to deliver high-tier quality software and AI-driven applications, such as audio transcription.",
                date: "JUL 2023 - DEC 2023",
            },
            type: { internship: "Intern" },
        },
        about: `
            <p>
            In 2016, during my middle school days, I embarked on a <span class="strong-text"
                >journey of curiosity and discovery</span
            >, tinkering with DIY drones, 3D printers, Arduino, and Raspberry Pi. This adventurous
            beginning served as a gateway, immersing me deeply into the realms of programming and web
            development. As I transitioned from hardware to the digital realm, I cultivated an affinity
            for <span class="strong-text">both front-end and back-end</span> development.
            </p>

            <p>
                Having recently <span class="strong-text"
                    >completed a Master of Science in Computer Science from UTT</span
                >, I bring with me not just academic credentials but substantial professional experience as
                well. My first foray into the professional tech world began with a six-month internship at
                <a
                    class="text-white hover:text-secondary font-semibold"
                    target="_blank"
                    href="https://grytics.com">Grytics</a
                >, where I honed my programming skills. This was followed by a second internship at
                <a
                    class="text-white hover:text-secondary font-semibold"
                    target="_blank"
                    href="https://careers.selectra.com/">Selectra</a
                >, working as a Full-stack Web Engineer. These experiences have equipped me with a solid
                foundation in both the theoretical and practical aspects of technology. It's now time for me
                to <span class="strong-text">seek the best opportunities to start my career</span> and make a
                significant impact in the tech industry.
            </p>

            <p>
                Despite my busy academic schedule, I make it a point to nurture <span class="strong-text"
                    >my love for side projects</span
                >. My ventures range from creating unique 3D printer projects along with FPV drones and even Web stuff such as Twitch or social networks with Artificial Intelligence - a testament to my enduring fondness for the blend of creativity and technology.
            </p>

            <p>
                Away from the screens and circuits, I'm an active individual with a keen interest in
                calisthenics, climbing and hiking. The thrill of a new trail or the satisfaction of a
                well-executed workout <span class="strong-text">keeps me grounded and invigorated</span>.
                Simultaneously, I'm continually broadening my horizons by delving into the world graphic design, a hobby that
                <span class="strong-text">adds a splash of artistic inspiration to my technically-oriented mindset</span>.
            </p>

            <p>
                When I reflect on my journey so far, I realize it's the perfect blend of code, creativity,
                and outdoor adventures that <span class="strong-text">keeps me excited about each day ahead</span>.
            </p>
        `,
    },
    fr: {
        hero: {
            quote: "Je développe des choses sur le Web pour ce petit Monde",
            title: "Ingénieur Web Full-stack",
        },
        footer: {
            github: { text: "", label: "Lien GitHub" },
            mail: { text: "", label: "Adresse mail" },
            linkedin: { text: "", label: "Lien Linkedin" },
            resume: { text: "Mon CV", label: "Fichier CV", url: "/resume_fr.pdf" },
        },
        button: {
            seeMore: "Voir plus",
            viewOn: "Regarder sur",
            back: "Retour",
        },
        nav: {
            about: "à propos",
            experience: "expérience",
            projects: "projets",
            skills: "compétences",
        },
        projects: {
            type: { personal: "Personnel", academic: "Académique" },
            sna: {
                date: "2024",
                title: "Comptes de Réseaux Sociaux Autonomes",
                desc: "Ce projet consistait à développer une solution d'automatisation des réseaux sociaux basée sur Python. Les principales fonctionnalités comprennent l'extraction de données, la génération de contenu assistée par IA, la publication automatique et l'engagement communautaire. Une architecture complète a été conçue pour gérer plusieurs comptes et tâches.",
                details: {
                    intro: "Ce projet a pour objectif de développer une <b>solution complète d'automatisation pour les réseaux sociaux</b>, utilisant <b>Flask, Vue.js, Node.js, Remotion, Redis, Celery, MySQL et Docker</b>. Les fonctionnalités clés de cette solution incluent l'extraction de données, la génération de contenu assistée par intelligence artificielle, la publication automatique. L'architecture conçue est robuste, permettant de <b>gérer simultanément plusieurs comptes et différentes tâches</b>.",
                    video: "Un exemple de cette solution peut être observé à travers une vidéo démonstrative. Le cœur du contenu vidéo, un poème, est généré par un modèle de langage à grande échelle (<b>LLM</b>). En complément, la vidéo intègre un fond libre de droits, soigneusement sélectionné et adapté pour l'occasion. Les <b>sous-titres</b>, enrichis d'emojis, sont synchronisés avec la </b>narration du texte</b> par une IA générative. Une bande sonore accompagne l'ensemble pour renforcer le tout.",
                    outro: "La vidéo finale est <b>publiée</b> sur le compte relatif avec une <b>description et une miniature</b> pour attirer et engager le public cible.",
                    media: {
                        video: "Exemple d'une vidéo",
                    },
                },
            },
            ml: {
                date: "2022",
                title: "Modèle de Machine Learning",
                desc: "Création d'un modèle d'apprentissage machine en Python pour prédire les revenus de tous types de magasins de détail en Norvège",
            },
            ayc: {
                date: "2022",
                title: "Chaîne Youtube Autonome",
                desc: "Ce projet impliquait la création d'une chaîne YouTube dédiée aux compilations quotidiennes des meilleurs clips de Twitch, le tout amélioré par des superpositions graphiques pour enrichir l'expérience utilisateur. Utilisant Python pour la gestion de la chaîne, les tâches comprenaient le scrapping de données, l'acquisition de ressources, la sélection puis la création de contenu et sa mise en ligne.",
                details: {
                    intro: "Il s'agit de <b>mon premier projet de programmation personnel</b>, et notamment mon apprentissage de <b>Python, des APIs, de FFmpeg, de Docker et de l'hébergement sur un VPS</b>. Il a consisté à développer une chaîne YouTube spécialisée dans les compilations quotidiennes des <b>meilleurs clips de Twitch</b>. L'objectif était d'enrichir <b>l'expérience utilisateur</b> grâce à des assets graphiques. Le projet repose sur l'API de Twitch pour le <b>scrapping et stockage<b> de données, il y a également une <b>acquisition</b> de ressources, la <b>sélection</b> de contenu, et sa <b>publication</b> automatique.",
                    video: "Chaque vidéo compilée présentait une <b>structure dynamique</b> : sur la gauche, en haut, un <b>sommaire</b> affichait les noms des streamers, à droite figurait le <b>clip Twitch</b> sélectionné, en bas à gauche la <b>vignette du jeu</b> correspondant, et en bas à droite le <b>titre du clip</b>. Des incitations au partage et à l'abonnement (<b>Call to Action</b>) étaient intégrées tout au long de la vidéo, complétées par une outro en fin de vidéo.",
                    thumbnail:
                        "Les <b>miniatures</b> de chaque vidéo étaient conçues pour attirer l'attention des spectateurs, avec des couleurs vives et des éléments graphiques accrocheurs. Les <b>streamers les plus populaires étaient mis en avant</b> au centre avec des images pré-définies, tandis que les photos de profil des autres streamers apparaissaient dans des cercles latéraux. Le numéro de l'épisode et une capture d'écran de deux clips viraux formaient l'arrière-plan, avec la possibilité de varier les couleurs du fond, du titre et des numéros selon <b>plusieurs combinaisons</b>.",
                    text: "Un <b>titre</b> était généré automatiquement pour chaque vidéo, mettant en avant les streamers populaires présents. Une <b>description</b> détaillée créait une timeline précise pour chaque clip inclus, facilitant ainsi la navigation dans la vidéo.",
                    media: {
                        video: "Extrait d'une vidéo",
                        cta: "Exemple de Call to Action",
                        thumbnail: "Miniature d'une vidéo",
                    },
                },
            },
            dw: {
                date: "2021",
                title: "Site Web Dynamique",
                desc: "Site de vaccination en HTML, CSS, PHP, SQL avec gestion des différentes fonctionnalités du point de vue du fournisseur",
            },
        },
        experience: {
            grytics: {
                title: "Ingénieur Développeur Assistant",
                desc: "Chez Grytics, j'ai effectué des tests fonctionnels et des preuves de concept en machine learning/IA pour améliorer leur application web. Travaillant de manière autonome sous la direction du lead développeur, j'ai affiné mes compétences dans le code maintenable et la résolution de problèmes efficace, contribuant à la robustesse de l'application et mettant en avant les améliorations futures possibles.",
                date: "FÉV 2023 - JUIL 2023",
            },
            selectra: {
                title: "Ingénieur Web Full-stack",
                desc: "Chez Selectra, j'ai intégré de nouvelles fonctionnalités, refactorisé des bases de données et des services, et résolu des problèmes en utilisant Vue.js et Laravel, améliorant ainsi la stabilité et la performance des plateformes. J'ai amélioré l'expérience utilisateur et l'efficacité du projet grâce à l'optimisation des processus et à l'intégration d'APIs entre les projets. J'ai travaillé dans un environnement monolithique résilient et rigoureux, visant à fournir des logiciels de haute qualité et des applications poussées utilisant l'IA, comme la transcription audio.",
                date: "JUIL 2023 - DÉC 2023",
            },
            type: { internship: "Stage" },
        },
        about: `
            <p>
            En 2016, pendant mes années de collège, j'ai commencé un <span class="strong-text"
                >voyage de curiosité et de découverte</span
            >, en bidouillant avec des drones FPV, des imprimantes 3D, Arduino et Raspberry Pi. Ce début a servi de porte d'entrée, me plongeant profondément dans les royaumes de la programmation et du développement web. En passant du hardware pure au domaine numérique, j'ai développé une affinité pour le développement <span class="strong-text">front-end et back-end</span>.
            </p>

            <p>
                Ayant récemment <span class="strong-text"
                    >obtenu un Diplôme d'ingénieur en Informatique et Systèmes d'Information de l'UTT</span
                >, je n'apporte pas seulement des compétences académiques mais aussi une expérience professionnelle grâce à mon parcours. Mon premier pas dans le monde informatique professionnel a commencé avec un stage de six mois chez
                <a
                    class="text-white hover:text-secondary font-semibold"
                    target="_blank"
                    href="https://grytics.com">Grytics</a
                >, où j'ai affiné mes compétences en programmation. Cela a été suivi par un deuxième stage chez
                <a
                    class="text-white hover:text-secondary font-semibold"
                    target="_blank"
                    href="https://careers.selectra.com/">Selectra</a
                >, travaillant en tant qu'Ingénieur Web Full-stack. Ces expériences m'ont doté d'une solide
                base dans les aspects théoriques et pratiques de la technologie. Il est maintenant temps pour moi
                de <span class="strong-text">chercher les meilleures opportunités pour démarrer ma carrière</span> et faire un
                impact significatif dans l'industrie technologique.
            </p>

            <p>
                Malgré mon emploi du temps chargé, je m'assure de nourrir <span class="strong-text"
                    >mon amour pour les side-projects</span
                >. Mes projets englobent de l'impression 3D, des drones FPV, divers thématiques du Web comme Twitch et les réseaux sociaux et l'Intelligence Artificielle - un témoignage de mon affection persistante pour le mélange de créativité et de technologie.
            </p>

            <p>
                Loin des écrans et des circuits, je suis une personne active avec un vif intérêt pour
                l'escalade, la calisthénie et la randonnée. L'excitation d'un nouveau sentier ou la satisfaction d'un
                entraînement bien exécuté <span class="strong-text">me garde ancré et revigoré</span>.
                Simultanément, je continue d'élargir mes horizons en explorant le monde du design graphique, un passe-temps qui
                <span class="strong-text">ajoute une touche d'inspiration artistique à mon esprit orienté techniquement</span
                >.
            </p>

            <p>
                Quand je réfléchis à mon parcours jusqu'à présent, je réalise que c'est le mélange parfait de code, de créativité,
                et d'aventures en plein air qui <span class="strong-text">me rend enthousiaste pour chaque jour à venir</span>.
            </p>
        `,
    },
};
